In [1]:

import numpy as np
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup
import time
s = Service(r'C:\Users\Qur\Desktop\chromedriver.exe')
driver = webdriver.Chrome(service=s)
link = driver.get('https://www.rozee.pk/job/jsearch/q/all/fin/1/fpn/0')

# List for Temperaroy store
job_title = []
location = []
salary_date_status = []
skills_required = []
while True:
    html = driver.page_source
    soup = BeautifulSoup(html,'lxml')
    divs = soup.find_all('div',class_ = 'job')
    for i in divs:
        try:
            job_title.append(i.find('h3',class_ ='s-18').find('bdi').text)
            location.append(i.find('bdi',class_="float-left").text)
            salary_date_status.append(i.find('div',class_ = 'col-md-12 float-left').text)
            skills_required.append(i.find('div',class_ = 'job-dtl clearfix').text)
        except:
            print(np.nan)
    try:
        
        next_button_xpath = '//a[@class="next" and contains(text(), "Next")]'
        driver.find_element(by = By.XPATH,value=next_button_xpath).click()
        # next_button = WebDriverWait(driver, 10).until(
        # EC.element_to_be_clickable((By.XPATH, next_button_xpath))
        # )
        # next_button.click()
        time.sleep(3)
    except:
        print('There is issue while clicking on Button Next')
        break

nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
There is issue while clicking on Button Next

In [2]:
import pandas as pd 
df = pd.DataFrame({
    'Job Title': job_title,
    'salary_date_status': salary_date_status,
    'location': location,
    'skills_required': skills_required
})

In [5]:
df.to_csv('Job_data.csv')

In [15]:
Job_df = pd.read_csv('Job_data.csv')
Job_df = Job_df.drop(columns='Unnamed: 0')
Job_df

,Job Title,salary_date_status,location,skills_required
0,Social Media Manager,"Jan 07, 20253 Years","Rayymen Technologies Private Limited, Lahore, ...",Social Media ManagementSocial Media HandlingSo...
1,Senior Project Manager,"Jan 07, 20256 Years150K - 200K","Rayymen Technologies Private Limited, Multiple...",Web Project ManagementAgile Project Management...
2,Project Coordinator,"Jan 07, 20251 Year","Rayymen Technologies Private Limited, Lahore, ...",Client DealingEnd to End SalesProject Management
3,Sales Executive,"Jan 07, 20251 Year40K - 50K","Rayymen Technologies Private Limited, Lahore, ...",Client DealingSalesEnd to End Sales
4,Magento Developer,"Jan 07, 20253 Years70K - 250K","Rayymen Technologies Private Limited, Multiple...",MySQLMagnetoHTMLPHP
...,...,...,...,...
482,Office ChildCare Specialist,"Jan 19, 20243 Years","Contour Software, Lahore, Pakistan",NaN
483,Senior Software Developer,"Nov 22, 20235 Years","Contour Software, Lahore, Pakistan",NaN
484,Senior Elastic Search Engineer,"Oct 27, 20237 Years","Contour Software, Multiple Cities, Pakistan",NaN
485,Accounts Executive,"Oct 26, 20232 Years","Contour Software, Karachi, Pakistan",NaN
486,Senior Software Developer (Interfaces),"Oct 05, 20235 Years","Contour Software, Lahore, Pakistan",NaN